bhoffman0/CSAwesome

_sources/Unit2-Using-Objects/topic-2-1-objects-intro-turtles.rst, _sources/Unit2-Using-Objects/topic-2-2-constructors.rst
changed text and added some questions
=> Revised 2.1 and 2.2

_sources/Unit2-Using-Objects/topic-2-2-constructors.rst
Added more multiple choice questions and changed numbering for the multiple-choice questions
=> Modified 2.2 to add some some more questions

.gitignore, _sources/Unit7-ArrayList/cookieOrderB.rst, pavement.py, sphinx_settings.json
Fixed the algorithm steps and added some distractors to the mixed up code (Parsons) problem
=> Fix and enhancment to Cookie Order B

_sources/Unit7-ArrayList/2019delimitersQ3a.rst
I added reveals so that students who think that they know what to do can try without help
=> Added reveals to not give things away if students don't want help

_sources/Unit7-ArrayList/2019delimitersQ3a.rst, _sources/Unit7-ArrayList/2019delimitersQ3b.rst, sphinx_settings.json
Test of making the reveals and contents of the reveals optional
=> Made reveals and contents optional

_sources/Unit4-Iteration/FRQcalendar.rst, _sources/Unit4-Iteration/FRQselfDivisorA.rst, _sources/Unit5-Writing-Classes/FRQstepTracker.rst
added reveals for FRQ calendar in unit 4. more to come!
=> added reveals

_sources/Unit8-2DArray/grayImageA.rst
Added reveal questions to  GrayImage A
=> Unit 8 FRQ Gray Image A

_sources/Unit8-2DArray/CBLabs.rst, _sources/Unit8-2DArray/pictureLabDay3.rst, _sources/Unit8-2DArray/pictureLabDay4.rst
Also changed some things in PL Day 3 to see if the embedded image/data file will work this time.
=> PictureLab Day 4 Addition

_sources/Unit8-2DArray/CBLabs.rst, _sources/Unit8-2DArray/pictureLabDay3.rst, _sources/Unit8-2DArray/pictureLabDay5.rst
Daphney is going to start working on adding content for the picturelab as well, I'm pushing what changes I have so she can build off them even thought they're not done yet.
=> Setting up for Daphney

_sources/Unit7-ArrayList/2013gridworldQ3A.rst, _sources/Unit7-ArrayList/topic-7-4-arraylist-algorithms.rst
I embedded the needed GridWorld .jar files and created 2 output testing functions. When I locally compiled the website the embedded data files seemed to turn all the text after their embedding red. I wasn't sure how to fix this.
=> Worked on the GridWorld Question

conf.py
I had to remove the script_files to get this to build on my machine
=> fix to conf.py to allow it to build

_sources/Unit8-2DArray/peer_int.rst
As I mentioned in Discord, I'm pretty sure this space is just a mistake that breaks the last two questions on this page.
=> Remove spurious space.

_sources/Unit2-Using-Objects/topic-2-5-methods-return.rst, _sources/Unit5-Writing-Classes/topic-5-4-accessor-methods.rst, _sources/Unit5-Writing-Classes/topic-5-6-writing-methods.rst
Tiny wording change. When I teach "assignment" is a particular notion that I talk about and try to be consistent about how I talk about it. But that may just be me.
=> saving in -> assigning to

_sources/Unit1-Getting-Started/csptransition.rst
This one I got carried away with. Did give me a chance to mention the refactoring button, assuming that's coming soon. (Though I guess we shouldn't merge this, assuming you want it, until the server switch happens.)
As I said, I totally get it if you don't wan this big an edit.
=> Edits on CSP transition page

_static/css/custom.css
Let me know what you think of this. Removed the background color and the extra padding and darkened the color a bit.
=> Change style of inline code.

_sources/Unit3-If-Statements/topic-3-5-compound-ifs.rst, _sources/Unit3-If-Statements/topic-3-6-DeMorgan.rst, _sources/Unit3-If-Statements/topic-3-8-summary.rst
There's plenty more to do along these lines but I was reading these chapters today and so I thought I'd fix these.
=> Adding code markup (``s) around a bunch of stuff in Unit3

_sources/Unit9-Inheritance/topic-9-6-polymorphism.rst
Mostly adding code formatting where needed in 9.6. Also made a couple small fixes to the code in two of the problems, in one case to remove an unneeded line and in the other to make sure it actually printed something as the question implied it would.
=> Some edits and code formatting to topic-9-6

_static/css/custom.css
=> Add a bit of spacing before paragraphs after code and videos

_sources/Unit4-Iteration/topic-4-1-while-loops.rst
Added a tiny bit to the section on infinite loops to point out that sometimes we write infinite loops on purpose. And added some code backticks and removed a redundant item from the summary.
=> Some edits to 4.1

_sources/Unit1-Getting-Started/topic-1-3-variables.rst, _sources/Unit1-Getting-Started/topic-1-4-assignment.rst, _sources/Unit1-Getting-Started/topic-1-5-shortcutoperators.rst, _sources/Unit1-Getting-Started/topic-1-7-summary.rst, _sources/Unit10-Recursion/topic-10-1-recursion-day1.rst, _sources/Unit2-Using-Objects/topic-2-10-summary.rst, _sources/Unit2-Using-Objects/topic-2-6-strings.rst, _sources/Unit2-Using-Objects/topic-2-7-string-methods.rst, _sources/Unit3-If-Statements/topic-3-1-booleans.rst, _sources/Unit3-If-Statements/topic-3-2-ifs.rst, _sources/Unit3-If-Statements/topic-3-5-compound-ifs.rst, _sources/Unit3-If-Statements/topic-3-7-comparing-objects.rst, _sources/Unit3-If-Statements/topic-3-8-summary.rst, _sources/Unit4-Iteration/ConsumerReviewLab.rst, _sources/Unit4-Iteration/FRQcalendar.rst, _sources/Unit4-Iteration/topic-4-2-for-loops.rst, _sources/Unit4-Iteration/topic-4-5-loop-analysis.rst, _sources/Unit5-Writing-Classes/APLine.rst, _sources/Unit6-Arrays/topic-6-2-traversing-arrays.rst, _sources/Unit7-ArrayList/topic-7-5-searching.rst
Woke up this morning feeling an urge to make our use of code backticks more consistent so here you go. I also couldn't resist a few edits of the wording in a few sections—you can see those in the diff because I've rewrapped the paragraphs.
One style question that it seems hasn't been resolved totally consistently through the book is how to refer to methods. Do we say:
> When you invoke the `toString` method ..
or:
> When you invoke the `toString()` method ...
My inclination would be to leave off the parens unless it's important to specify the argument signature, `equals(Object)` or whatever.
=> Adding many backticks

_sources/Unit5-Writing-Classes/topic-5-2-writing-constructors.rst
This is more by way of a first draft of this new material. I haven't gone over it with a fine-tooth comb yet but wanted to let you see what I've got so far.
=> Working on stuff about constructors in 5.2

_sources/Unit2-Using-Objects/topic-2-5-methods-return.rst, _sources/Unit5-Writing-Classes/community-challenge.rst, _sources/Unit5-Writing-Classes/topic-5-1-parts-of-class.rst, _sources/Unit5-Writing-Classes/topic-5-2-writing-constructors.rst, _sources/Unit5-Writing-Classes/topic-5-4-accessor-methods.rst, _sources/Unit5-Writing-Classes/topic-5-5-mutator-methods.rst, _sources/Unit5-Writing-Classes/topic-5-6-writing-methods.rst, _sources/Unit5-Writing-Classes/topic-5-9-this.rst
Mostly editing the challenge exercises in Unit 5 to remove the requirement to add a no-args constructor and changing the unit tests accordingly. I also added subsection headers to 5.2 and fixed an underline in 2.5 and removed some visualizer links.
=> Updating U5 challenges to remove no-args constructor

_sources/Unit2-Using-Objects/topic-2-5-methods-return.rst, _sources/Unit2-Using-Objects/topic-2-6-strings.rst, _sources/Unit5-Writing-Classes/topic-5-4-accessor-methods.rst
This adventure started with a simple desire to consolidate the nearly duplicated discussion of `toString` in 2.5 and 5.4. I decided that that best lived in 5.4. Since that slimmed down 2.5 I got to looking at it and felt like it could be connected to what came before a bit more strongly. (Also it had some dangling back references to setters that hadn't actually been discussed yet, I don't think.)
Anyway, another big bunch of edits. If you like this, I'll probably find the right place to bring in the "setters" terminology to go along with the "getters".
=> Edits to 2.5

_static/css/custom.css
=> Space out the bulleted list in the summary a bit.

_sources/Unit5-Writing-Classes/topic-5-4-accessor-methods.rst, _sources/Unit5-Writing-Classes/topic-5-5-mutator-methods.rst
This was mostly intended to flow through the getter/setter terminology we started using in Unit 2. However I also threw in some editorializing about how you _shouldn't_ actually reflexively write either getters or setters.
=> Edits/topics 5.4 5.5

_sources/Unit2-Using-Objects/topic-2-3-methods-no-params.rst, _sources/Unit4-Iteration/topic-4-1-while-loops.rst, _sources/Unit5-Writing-Classes/topic-5-4-accessor-methods.rst
Noticed these while I was trying to figure out where we explained about the `return` statement.
=> Small edits, mostly formatting.

_sources/Unit9-Inheritance/topic-9-2-constructors.rst
Tried to explain a bit of the rationale behind `super` calls in constructors and to take out suggestions that it's a good practice to always write no-arg constructors.
=> Edits to 9.2

_sources/Unit1-Getting-Started/topic-1-2-java-intro.rst, _static/css/custom.css
I get really frustrated when students don't even *try* to read the error messages. So here's some stuff to encourage them to do so and give them some pointers on how to.
=> Some elaboration of how to read compiler errors.

_static/css/custom.css
=> Another take at widths.

_sources/Unit1-Getting-Started/topic-1-2-java-intro.rst, _sources/Unit1-Getting-Started/topic-1-6-casting.rst
Shortening code in 1.6
Adding buddy programming to 1.2
=> edits to 1.2 and 1.6

_sources/Unit1-Getting-Started/topic-1-6-casting.rst
At this point I'm just procrastinating on other stuff (like my CTE coursework). I took out the example that used the unicode escape because I think in this world of ubiquitous UTF-8 they're less common and they weren't really explained anyway.
=> A bit of work on Unicode challenge in 1.6

_sources/Unit1-Getting-Started/preface.rst
I think maybe you meant to update this too?
=> Update copyright notices in preface.

_sources/Unit4-Iteration/FRQcalendar.rst, _sources/Unit4-Iteration/FRQselfDivisorA.rst, _sources/Unit4-Iteration/FRQstringScrambleA.rst, _sources/Unit4-Iteration/topic-4-1-while-loops.rst, _sources/Unit4-Iteration/topic-4-2-for-loops.rst, _sources/Unit4-Iteration/topic-4-3-strings-loops.rst, _sources/Unit4-Iteration/topic-4-4-nested-loops.rst, _sources/Unit4-Iteration/topic-4-5-loop-analysis.rst, _sources/Unit4-Iteration/topic-4-6-group-mod.rst, _sources/Unit4-Iteration/topic-4-6-summary.rst, _sources/Unit4-Iteration/topic-4-7-practice-mixed-code.rst, _sources/Unit4-Iteration/topic-4-8-practice-coding.rst
This on entailed much less change after the reformatter ran; just adding a couple sets of braces. And I ran all the code.
=> Ran reformatter on Unit 4 and fixed a few things by hand.

_sources/FreeResponse/StudentAnswerSheetB.rst, _sources/HiddenFiles/topic-8-4-toggle-write-code.rst, _sources/TimedTests/test3.rst, _sources/Unit3-If-Statements/topic-3-3-if-else.rst, _sources/Unit4-Iteration/topic-4-8-practice-coding.rst, _sources/Unit5-Writing-Classes/topic-5-7-static-vars-methods.rst, _sources/Unit6-Arrays/ArrayPractice.rst, _sources/Unit6-Arrays/arrayExam.rst, _sources/Unit6-Arrays/horseBarnA.rst, _sources/Unit6-Arrays/horseBarnB.rst, _sources/Unit7-ArrayList/2013gridworldQ3A.rst, _sources/Unit7-ArrayList/ssHardMC.rst, _sources/Unit7-ArrayList/stringScrambleB.rst, _sources/Unit7-ArrayList/topic-7-2-arraylist-methods.rst, _sources/Unit8-2DArray/Array2dCodePractice.rst, _sources/Unit8-2DArray/routeCipherA.rst, _sources/Unit8-2DArray/topic-8-2-2D-array-loops-Day2.rst
I noticed some 1 line if statements like ``if (t > maxTemp) maxTemp = t;`` and did a global replace to add in newlines, spacing, and curly braces.  Proud of my regexp: s/([ ]*)((else if|if|else)\s*\(.*\))([^\n]*;)/$1$2\n$1{\n$1    $4\n$1}/g
=> Global replace to add \n and {} to 1 line if/else statements

_static/js/renumber.js
Noticed this while working on actually adding a new chapter to BHSawesome. Moot in this branch since we have renumbering off but if we ever wanted to use it (unlikely) this should be in there and this will keep master more in sync with my branch.
=> Fix the title if we are renumbering.

_sources/Unit2-Using-Objects/topic-2-1-objects-intro-turtles.rst
Not sure why your script missed this one. It's the only one missed.
=> one svg time estimate missed and link fixes

_sources/Unit1-Getting-Started/topic-1-4-assignment.rst, _sources/index.rst
Borrowed the bhsawesome 1.4 edits but added edits.
I removed the ..note styling. I've been using the ..note blue box for short important facts or errors, instead of footnotes or asides, but willing to discuss. 
@gigamonkey, you may want to cherry-pick the "`=` in first paragraph" and "Edit: Remainder gives you remainder" commits.
=> edits/1 4 cherry pick bhsawesome + edits

_sources/Unit1-Getting-Started/topic-1-9-practice-coding.rst
For the last 3 problems, I tried to add slightly better directions and more flexibility in the patterns and better feedback, without changing the problems.
=> Edits to 1-9 for slightly better directions and feedback from autograding code

_sources/Unit5-Writing-Classes/topic-5-1-parts-of-class.rst, _sources/Unit5-Writing-Classes/topic-5-2-writing-constructors.rst, _sources/Unit5-Writing-Classes/topic-5-8-scope-access.rst
I think I messed these up when we were moving down { after method headers.
@gigamonkey pull these into your book too.
=> Fixing Unit 5 click-correct exercises

_sources/Unit3-If-Statements/topic-3-8-summary.rst
I'm just going to go ahead and cowboy merge this so I can then merge it into BHSawesome. But the PR is here so you can see what I did.
=> Fix some backticks.

_sources/Unit3-If-Statements/topic-3-5-compound-ifs.rst
Another one I'm going to cowboy in.
=> Missing backtick.

_sources/Unit6-Arrays/topic-6-2-traversing-arrays.rst
=> Fix description of problem code that is not quite identical.

_sources/Unit6-Arrays/topic-6-4-array-algorithms.rst
=> Add some missing braces and indentation.

_sources/Unit7-ArrayList/topic-7-1-arraylist-basics.rst, _sources/Unit7-ArrayList/topic-7-2-arraylist-methods.rst, _sources/Unit7-ArrayList/topic-7-3-arraylist-loops.rst
Did not do the type inference syntax
=> Cherry pick u7 peter edits

_sources/Unit7-ArrayList/listPractice.rst, _sources/Unit9-Inheritance/topic-9-4-super.rst
=> Two bug fixes pointed out by teachers

_sources/Unit9-Inheritance/ooSummary.rst, _sources/Unit9-Inheritance/topic-9-3-overriding.rst, _sources/Unit9-Inheritance/topic-9-5-hierarchies.rst, _sources/Unit9-Inheritance/topic-9-6-polymorphism.rst
My recent changes in one tidy PR.
=> Unit 9 bhsawesome edits

_sources/Unit1-Getting-Started/preface.rst
Since we're talking about the license, figured it would be a good time to update these.
=> Updating copyright years to include 2024

_sources/Unit8-2DArray/Array2dMoreCodePractice.rst
=> Fixed the indentation

_sources/Unit6-Arrays/MoreArrayPractice.rst, _sources/Unit6-Arrays/toctree.rst
Added some 1D array write code problems.
=> Added some 1D array write code problems.

_sources/Unit1-Getting-Started/topic-1-4-assignment.rst, _sources/Unit1-Getting-Started/topic-1-6-casting.rst, _sources/index.rst
Bringing back in some edits to exercises from csawesome2 in 1.3 and 1.4
=> Unit 1 Edits borrowed back from csawesome2

_sources/HiddenFiles/topic-10-4-toggle-write-code.rst, _sources/HiddenFiles/topic-7-9-toggle-write-code.rst, _sources/HiddenFiles/topic-8-4-toggle-write-code.rst, _sources/HiddenFiles/topic-9-10-toggle-write-code.rst, _sources/TimedTests/Exercises.rst, _sources/Unit3-If-Statements/topic-3-13-more-practice-coding.rst, _sources/Unit4-Iteration/topic-4-7-practice-mixed-code.rst, _sources/Unit5-Writing-Classes/midterm_unit5.rst, _sources/Unit6-Arrays/MoreArrayPractice.rst, _sources/Unit8-2DArray/Array2dMoreCodePractice.rst, _sources/Unit9-Inheritance/ooCodePractice.rst, _sources/Unit9-Inheritance/ooParsonsPractice.rst, _sources/_hidden/Ex-array-orig.rst
The term function was used in some exercises instead of method. These have been replaced.
=> Replacing function with method

_sources/Unit6-Arrays/ArrayPractice.rst
This stuck out to me while I was doing the 6.8. Please let me know if it was intended!
=> remove extraneous semicolon
